// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("ActivityTransaction")]
    public partial class ActivityTransaction
    {
        [Key]
        public Guid Id { get; set; }
        [Key]
        public Guid TripProgramActivityId { get; set; }
        [Key]
        public Guid CustomerId { get; set; }

        [ForeignKey(nameof(CustomerId))]
        [InverseProperty("ActivityTransactions")]
        public virtual Customer Customer { get; set; }
        [ForeignKey(nameof(TripProgramActivityId))]
        [InverseProperty("ActivityTransactions")]
        public virtual TripProgramActivity TripProgramActivity { get; set; }
    }
}