// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("Activity")]
    public partial class Activity
    {
        public Activity()
        {
            TripProgramActivities = new HashSet<TripProgramActivity>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public Guid PlaceId { get; set; }

        [ForeignKey(nameof(PlaceId))]
        [InverseProperty("Activities")]
        public virtual Place Place { get; set; }
        [InverseProperty(nameof(TripProgramActivity.Activity))]
        public virtual ICollection<TripProgramActivity> TripProgramActivities { get; set; }
    }
}