// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("Customer")]
    public partial class Customer
    {
        public Customer()
        {
            ActivityTransactions = new HashSet<ActivityTransaction>();
            HotelBookings = new HashSet<HotelBooking>();
        }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int? Age { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string Gender { get; set; }
        [Required]
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(50)]
        public string PassportId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Balance { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty(nameof(ActivityTransaction.Customer))]
        public virtual ICollection<ActivityTransaction> ActivityTransactions { get; set; }
        [InverseProperty(nameof(HotelBooking.Cutomer))]
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
    }
}