// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("HotelReservationType")]
    public partial class HotelReservationType
    {
        public HotelReservationType()
        {
            HotelBookings = new HashSet<HotelBooking>();
        }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Code { get; set; }
        [Key]
        public Guid Id { get; set; }

        [InverseProperty(nameof(HotelBooking.HotelReservationType))]
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
    }
}