// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("Hotel")]
    public partial class Hotel
    {
        public Hotel()
        {
            HotelBookings = new HashSet<HotelBooking>();
        }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? CostPerDayFully { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? CostPerDayHalfBoard { get; set; }
        [Key]
        public Guid Id { get; set; }
        public Guid CityId { get; set; }

        [ForeignKey(nameof(CityId))]
        [InverseProperty("Hotels")]
        public virtual City City { get; set; }
        [InverseProperty(nameof(HotelBooking.Hotel))]
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
    }
}