// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("HotelBooking")]
    public partial class HotelBooking
    {
        public Guid? RoomReservationTypeId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Cost { get; set; }
        public Guid? HotelReservationTypeId { get; set; }
        [Key]
        public Guid CutomerId { get; set; }
        [Key]
        public Guid ProgramId { get; set; }
        [Key]
        public Guid HotelId { get; set; }

        [ForeignKey(nameof(CutomerId))]
        [InverseProperty(nameof(Customer.HotelBookings))]
        public virtual Customer Cutomer { get; set; }
        [ForeignKey(nameof(HotelId))]
        [InverseProperty("HotelBookings")]
        public virtual Hotel Hotel { get; set; }
        [ForeignKey(nameof(HotelReservationTypeId))]
        [InverseProperty("HotelBookings")]
        public virtual HotelReservationType HotelReservationType { get; set; }
        [ForeignKey(nameof(ProgramId))]
        [InverseProperty("HotelBookings")]
        public virtual Program Program { get; set; }
        [ForeignKey(nameof(RoomReservationTypeId))]
        [InverseProperty("HotelBookings")]
        public virtual RoomReservationType RoomReservationType { get; set; }
    }
}