// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("Place")]
    public partial class Place
    {
        public Place()
        {
            Activities = new HashSet<Activity>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public Guid CityId { get; set; }
        [StringLength(300)]
        public string Address { get; set; }
        [Column(TypeName = "decimal(8, 8)")]
        public decimal? Longitude { get; set; }
        [Column("latitude", TypeName = "decimal(8, 8)")]
        public decimal? Latitude { get; set; }

        [InverseProperty(nameof(Activity.Place))]
        public virtual ICollection<Activity> Activities { get; set; }
    }
}