// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("Program")]
    public partial class Program
    {
        public Program()
        {
            HotelBookings = new HashSet<HotelBooking>();
            TripProgramActivities = new HashSet<TripProgramActivity>();
        }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int? Duration { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Cost { get; set; }
        [StringLength(50)]
        public string Description { get; set; }
        [Key]
        public Guid Id { get; set; }
        public Guid CityId { get; set; }

        [ForeignKey(nameof(CityId))]
        [InverseProperty("Programs")]
        public virtual City City { get; set; }
        [InverseProperty(nameof(HotelBooking.Program))]
        public virtual ICollection<HotelBooking> HotelBookings { get; set; }
        [InverseProperty(nameof(TripProgramActivity.Program))]
        public virtual ICollection<TripProgramActivity> TripProgramActivities { get; set; }
    }
}