// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace TourimAdventures.Entity.Entity
{
    [Table("TripProgramActivity")]
    public partial class TripProgramActivity
    {
        public TripProgramActivity()
        {
            ActivityTransactions = new HashSet<ActivityTransaction>();
        }

        public Guid TripId { get; set; }
        public Guid ProgramId { get; set; }
        public Guid ActivityId { get; set; }
        public bool IsMandatory { get; set; }
        [Key]
        public Guid Id { get; set; }

        [ForeignKey(nameof(ActivityId))]
        [InverseProperty("TripProgramActivities")]
        public virtual Activity Activity { get; set; }
        [ForeignKey(nameof(ProgramId))]
        [InverseProperty("TripProgramActivities")]
        public virtual Program Program { get; set; }
        [ForeignKey(nameof(TripId))]
        [InverseProperty("TripProgramActivities")]
        public virtual Trip Trip { get; set; }
        [InverseProperty(nameof(ActivityTransaction.TripProgramActivity))]
        public virtual ICollection<ActivityTransaction> ActivityTransactions { get; set; }
    }
}